version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8

    commands: 
      - echo Nothing to Install

  pre_build:
    commands:
      - echo Nothing to do in the pre-build phase
      - git clone https://github.com/juanpcamacho/application.git /timeoff-management
      - cd /timeoff-management
      - npm install
      - pm2 start npm --name "WebApp" --cwd /timeoff-management -- start

  
  build:
    commands:
      - echo Build start on 'date'
      - npm test
  
  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  files:
    - '**/*'
